import { mkdir, writeFile, copyFile, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';

// The public website is deliberately small: reusable templates, ordinary HTML,
// no client framework, and no connection to the internal operations application.
const origin = 'https://www.nanascozycorner.com';
const phone = '<a href="tel:+14144426262">414-442-6262</a>';
const email = '<a href="mailto:Info@nanascozycorner.com">Info@nanascozycorner.com</a>';
const directions = 'https://www.google.com/maps/search/?api=1&query=4006%20N%2042nd%20Street%2C%20Milwaukee%2C%20WI%2053216';
const escape = s => String(s).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const button = (href, label, secondary = false) => `<a class="button${secondary ? ' secondary' : ''}" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
const actions = () => `<div class="actions">${button('/enrollment.html', 'Check availability')}${button('/schedule-a-tour.html', 'Request a tour', true)}</div>`;
const heading = (eyebrow, title, description = '') => `<div class="section-heading"><p class="eyebrow">${eyebrow}</p><h2>${title}</h2>${description ? `<p>${description}</p>` : ''}</div>`;
const section = content => `<section class="section container">${content}</section>`;
const cards = items => `<div class="card-grid">${items.map(([label,title,body,href])=>`<article class="card"><p class="eyebrow">${label}</p><h3>${title}</h3><p>${body}</p>${href ? `<a class="text-link" href="${href}">Learn more <span aria-hidden="true">→</span></a>` : ''}</article>`).join('')}</div>`;
const faq = items => `<div class="faq-list">${items.map(([q,a])=>`<details><summary>${q}</summary><div><p>${a}</p></div></details>`).join('')}</div>`;
const hero = (eyebrow, title, body, cta = actions()) => `<section class="page-hero container"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${body}</p>${cta}</section>`;
const closing = (title = 'Let’s find the right start for your family.') => `<section class="closing container"><div><p class="eyebrow">Your next step</p><h2>${title}</h2><p>Tell us your child’s age and when you need care. We’ll talk through availability and next steps.</p></div>${actions()}</section>`;
const steps = () => `<ol class="steps"><li><span>01</span><h3>Tell us what you need</h3><p>Start with your child’s age, your schedule, and when you hope to begin.</p></li><li><span>02</span><h3>Get to know Nana’s</h3><p>Talk with our team and arrange a visit to explore the classroom and ask questions.</p></li><li><span>03</span><h3>Plan your child’s start</h3><p>Once a place is confirmed, we’ll walk through enrollment paperwork and preparation.</p></li></ol>`;
const input = (name,label,type='text',extra='') => `<label>${label}<input name="${name}" type="${type}" maxlength="160" ${extra}></label>`;
const select = (name,label,values,required=false) => `<label>${label}<select name="${name}" ${required?'required':''}><option value="">Choose an option</option>${values.map(v=>`<option>${v}</option>`).join('')}</select></label>`;
const commonFields = () => `${input('parent_name','Your name *','text','autocomplete="name" required')}${input('contact','Phone number or email *','text','required aria-describedby="contact-help"')}<p id="contact-help" class="field-help full">Use the contact detail you would like our team to reply to.</p>`;
const ageField = () => input('child_age', 'Child’s age *', 'text', 'required placeholder="For example, 8 months or 2 years"');
const startField = () => select('start_timing','When do you need care?',['As soon as a place is available','Within 1 month','Within 2–3 months','Later / planning ahead','Not sure yet'],true);
const notes = (label='Anything else we should know? (optional)') => `<label class="full">${label}<textarea name="message" rows="3" maxlength="1200" aria-describedby="privacy-help"></textarea></label>`;
const inquiry = (kind,title,fields) => `<section class="section container form-section" id="inquiry"><div class="form-intro"><p class="eyebrow">Let’s talk</p><h2>${title}</h2><p>Prefer a conversation? Call ${phone}.</p><p><strong>Monday–Friday<br>6 a.m.–6 p.m.</strong></p><div class="quiet-card"><h3>What happens next?</h3><p>Our team will discuss your needs and confirm the next step. A request does not reserve a place or confirm a tour.</p></div></div><div class="form-card"><p data-delivery-message>Share a few details below to prepare an email. You’ll review and send it from your email app.</p><form data-inquiry="${kind}" action="/api/inquiries" method="post"><input type="hidden" name="kind" value="${kind}"><div class="fields">${fields}<label class="honeypot" aria-hidden="true">Leave this field empty<input name="website" tabindex="-1" autocomplete="off"></label><p id="privacy-help" class="field-help full">Please leave out medical records, income documents, Social Security numbers, and children’s full names. Read our <a href="/privacy.html">website privacy information</a>.</p><div class="challenge full" data-challenge></div><button class="button full" type="submit" data-submit>Review email <span aria-hidden="true">→</span></button></div><p class="form-status" role="status" aria-live="polite" tabindex="-1"></p></form><div class="email-draft" hidden><h3>Your email is ready to review.</h3><p>Nothing has been sent yet. Open your email app and press Send, or copy the message and email it to ${email}.</p><label>Your message<textarea data-draft rows="7" readonly></textarea></label><div class="actions"><a class="button" data-email-link href="mailto:Info@nanascozycorner.com">Open email app <span aria-hidden="true">↗</span></a><button class="button secondary" type="button" data-copy>Copy message</button></div><p data-copy-status role="status"></p></div><noscript><p>The email helper needs JavaScript. You can still call ${phone} or email ${email} with your request.</p></noscript></div></section>`;

const pages = [
{file:'index.html',title:'Infant & Toddler Childcare in Milwaukee | Nana’s Cozy Corner',description:'A cozy start for infants and toddlers in Milwaukee. Explore care for ages 0–3 at Nana’s Cozy Corner, Monday–Friday, 6 a.m.–6 p.m. Ask about availability.',body:`
<section class="home-hero container"><div class="hero-copy"><p class="eyebrow"><span class="tiny-sun" aria-hidden="true">✳</span> Milwaukee childcare · Ages 0–3</p><h1>Little beginnings.<br><em>A whole lot of love.</em></h1><p class="lead">Infant and toddler care that feels like a warm welcome. At Nana’s Cozy Corner, little ones learn, grow, and belong—and families have a partner from the start.</p>${actions()}<p class="hero-detail">Monday–Friday, <strong>6 a.m.–6 p.m.</strong><br>4006 N 42nd Street · Milwaukee, WI 53216</p></div><div class="hero-art"><img src="/assets/hero-classroom.png" width="560" height="420" alt="Nana’s Cozy Corner brand artwork showing shared story time" fetchpriority="high"><div class="art-caption"><span aria-hidden="true">♡</span><div><strong>Small moments. Meaningful growth.</strong><p>A place to learn, grow, and belong.</p></div></div></div></section>
<div class="facts-band"><div class="container"><span>Infant & toddler care</span><span>Early Head Start partnership</span><span>Milwaukee · 53216</span><a href="tel:+14144426262">Let’s talk: 414-442-6262 <span aria-hidden="true">↗</span></a></div></div>
${section(heading('The first three years','Care for their stage.<br>Support for your family.','From the first small discoveries to big “I did it!” moments, children need care that grows with them.')+cards([['Infants','A gentle beginning','Responsive care, familiar routines, and time to bond, explore, and discover. Ask us about the minimum starting age and current openings.','/infant-care.html'],['Toddlers','Room to become themselves','Songs, stories, movement, and playful learning support growing language, confidence, and independence.','/toddler-care.html'],['Early Head Start','Extra support, early on','Eligible families may receive no-cost services through our Early Head Start partnership. We’ll help you understand the next step.','/early-head-start.html']]))}
<section class="sage-band"><div class="container split"><div>${heading('More than a daily routine','A little corner of<br>comfort and connection.')}<p>You know your child best. We bring care, patience, and a belief in what the early years can be. Together, we help your child feel at home.</p><a class="text-link" href="/about.html">Get to know Nana’s <span aria-hidden="true">→</span></a></div><div class="value-list"><article><span>01</span><div><h3>Warm, responsive care</h3><p>Daily routines make space for comfort, connection, and your child’s individual needs.</p></div></article><article><span>02</span><div><h3>Learning through play</h3><p>Everyday stories, sounds, movement, and discovery help little learners grow.</p></div></article><article><span>03</span><div><h3>A partnership with you</h3><p>Your questions, observations, and family routines belong in the conversation.</p></div></article></div></div></section>
${section(heading('From hello to a happy start','Getting started can be simple.')+steps())}
${section(`<div class="support-banner"><div><p class="eyebrow">A schedule that supports your day</p><h2>Here from 6 a.m. to 6 p.m.</h2><p>Monday–Friday care in Milwaukee. Have questions about Early Head Start, your care schedule, or transportation? Let’s talk through what may be available for your family.</p></div>${button('/contact.html','Ask a question',true)}</div>`)}
${section(`<div class="split"><div>${heading('A few helpful answers','Before your first hello.')}<p>Looking for another age group? Explore all of our <a href="/programs.html">childcare programs</a>.</p></div>${faq([['What ages should I ask about?','Our current enrollment focus is infants and toddlers, ages 0–3. Contact our team to confirm the minimum enrollment age, the right classroom, and availability for your child.'],['What are your hours?','Nana’s Cozy Corner operates Monday–Friday, 6 a.m.–6 p.m. Ask our team about holiday closures and the schedule you need.'],['How do I find out about openings and tuition?','Call or email with your child’s age, your preferred start date, and the days and hours you need. Our team will confirm availability, current rates, and any applicable support.'],['Can I visit before deciding?','Yes. Request a tour and tell us when you are available. Our team will confirm a time before your visit.']])}</div>`)}${closing()}`},
{file:'programs.html',title:'Childcare Programs in Milwaukee | Nana’s Cozy Corner',description:'Explore infant, toddler, preschool, and school-age care at Nana’s Cozy Corner in Milwaukee. Our enrollment focus is ages 0–3. Ask about the right program.',body:hero('Programs at Nana’s','Growing, one little<br>discovery at a time.','Explore care that follows your child’s stage, with infant and toddler care at the heart of our current enrollment focus.')+section(cards([['Infants','Comfort, connection, discovery','Responsive feeding, rest, diapering, sensory play, and early communication. Ask about our minimum starting age.','/infant-care.html'],['Toddlers','Curiosity with a caring guide','Language, movement, social play, and early independence, supported by gentle routines.','/toddler-care.html'],['Preschool · Ages 3–5','Ready for the next chapter','Play-based experiences support creativity, problem-solving, early literacy, and school readiness. Ask about current options.','/enrollment.html'],['School age','Support around the school day','Ask about before- and after-school care, school connections, schedules, and availability.','/contact.html']]))+section(heading('For every stage','A conversation about your child comes first.','Classroom placement and availability depend on your child’s age and the care you need. Tell us about siblings, timing, and your schedule so we can discuss the best fit.')+actions())+closing()},
{file:'infant-care.html',title:'Infant Daycare in Milwaukee | Nana’s Cozy Corner',description:'Explore infant care at Nana’s Cozy Corner in Milwaukee: responsive routines, early discovery, and parent partnership. Open Monday–Friday, 6 a.m.–6 p.m.',body:hero('Infant care · Milwaukee','A gentle start.<br>A caring connection.','Choosing care for your baby is a big decision. We make space to talk about your routines, your questions, and what helps your child feel comfortable.')+section(cards([['Comfort','Responsive daily care','Feeding, rest, diapering, and bonding are meaningful parts of an infant’s day. Talk with our team about your baby’s individual routine.'],['Discovery','Small moments of learning','Songs, simple stories, sensory experiences, and warm interaction support early communication and curiosity.'],['Partnership','Your family is part of the plan','Share what your baby enjoys, how they settle, and what you want to know about their day.']]))+section(`<div class="split"><div>${heading('Questions for your visit','Let’s talk about your baby’s day.')}<p>Bring your questions about rest, feeding, care routines, classroom staffing, communication, and starting care.</p></div>${faq([['How young can my child start?','Please confirm the minimum enrollment age with our team before planning your start date. Our ages 0–3 focus does not mean every age has an available place.'],['What should I bring for infant care?','Our team will share the current supplies and paperwork checklist as part of enrollment. During a tour, ask about feeding supplies, extra clothes, and how personal items are handled.'],['When is infant care available?','The center operates Monday–Friday, 6 a.m.–6 p.m. Contact us to discuss your specific care schedule and current infant openings.']])}</div>`)+closing('Your baby’s first hello starts with a conversation.')},
{file:'toddler-care.html',title:'Toddler Daycare in Milwaukee | Nana’s Cozy Corner',description:'Toddler childcare in Milwaukee with playful learning, gentle routines, and family partnership. Explore Nana’s Cozy Corner, Monday–Friday, 6 a.m.–6 p.m.',body:hero('Toddler care · Milwaukee','Big curiosity.<br>A cozy place to grow.','For little ones finding their words, testing new skills, and exploring the world, our toddler program pairs playful discovery with caring guidance.')+section(cards([['Language','So much to say','Songs, stories, conversation, and naming feelings help toddlers practice communication throughout the day.'],['Movement','So much to explore','Hands-on play and movement give growing children ways to discover, try, and build confidence.'],['Independence','“I can do it!” moments','Gentle routines and support help children practice new skills, choices, and social play.']]))+section(`<div class="split"><div>${heading('A growing partnership','Your toddler’s next step,<br>with you alongside.')}<p>Tell us about your child’s interests and routines. Ask about classroom transitions, daily communication, and how our team approaches new skills.</p></div>${faq([['Which classroom is right for my toddler?','Contact us with your child’s current age and care needs. Our team will discuss the appropriate classroom and available places.'],['Can you help me understand Early Head Start?','Yes. Eligible families with young children may receive Early Head Start services. Our team can help you explore program eligibility and the application process.'],['How do I get started?','Ask about availability or request a tour. Share your child’s age, when you need care, and the days and hours that fit your family.']])}</div>`)+closing()},
{file:'about.html',title:'About Nana’s Cozy Corner | Milwaukee Childcare',description:'Meet the values behind Nana’s Cozy Corner in Milwaukee: warm care, early learning, family legacy, and partnership with parents.',body:hero('The heart of Nana’s','Care is personal here.','At Nana’s Cozy Corner, early childhood education is part of our family’s legacy. We believe a warm, positive beginning helps children grow into confident, curious learners.',button('/schedule-a-tour.html','Come get to know us'))+section(`<div class="story-layout"><p class="large-quote">“To treat every child<br>as if they were<br><em>our own.”</em></p><div><p class="eyebrow">Our commitment</p><h2>A place to learn,<br>grow, and belong.</h2><p>Led by Ms. Kelly, Nana’s Cozy Corner is rooted in a family tradition of caring for and educating young children.</p><p>We believe children thrive when they feel supported, encouraged, and understood. That belief shapes how we care for each child and how we partner with families.</p><p>Get to know our team in person. Bring your questions about our experience, classroom routines, and approach to early learning.</p></div></div>`)+section(cards([['Our care','Warmth with purpose','A patient, nurturing environment where children can feel comfortable and ready to explore.'],['Our learning','Room for discovery','Play and everyday interactions make space for growing communication, confidence, and curiosity.'],['Our families','A shared beginning','We welcome parents’ questions and insights. You are an important partner in your child’s care.']]))+closing('Come see whether Nana’s feels right for your family.')},
{file:'early-head-start.html',title:'Early Head Start in Milwaukee | Nana’s Cozy Corner',description:'Learn about Early Head Start support at Nana’s Cozy Corner for eligible families with children ages 0–3. Ask about eligibility and the next step.',body:hero('Early Head Start · Milwaukee','Extra support.<br>Right from the start.','Through our Early Head Start partnership, eligible families with children ages 0–3 may receive no-cost services that support early learning, healthy development, and family goals.',button('#inquiry','Ask about Early Head Start'))+section(cards([['Learning','Care and early discovery','Nurturing routines and playful experiences support children’s development in the earliest years.'],['Development','Support for growing children','Services may include health and developmental screenings, referrals, and support for children with disabilities.'],['Family','A partner in the process','Families can explore resources, goals, and next steps with program staff.']]))+section(`<div class="split"><div>${heading('Where to begin','You don’t have to work it out alone.')}<p>Eligibility and available places are reviewed through the program. Ask about current application ages, service area, family circumstances, and required documents.</p><p>Our published EHS service area includes Milwaukee ZIP codes 53205, 53209, 53210, 53212, and 53216. Contact the team to confirm current coverage.</p><p>General Early Head Start services may also support expectant families; ask the program about the option that fits your needs.</p></div><div class="quiet-card"><h3>A first question is enough.</h3><p>This website does not determine eligibility or complete an EHS application. You do not need to share benefit, income, medical, or housing documents here.</p><p>For program information, visit <a href="https://wisconsinearlychildhood.org/early-head-start/" target="_blank" rel="noopener">Wisconsin Early Childhood Association</a>, or contact our team for help getting started.</p></div></div>`)+inquiry('ehs','Ask about EHS support.',commonFields()+ageField()+input('zip_code','ZIP code (optional)','text','inputmode="numeric" pattern="[0-9]{5}"')+notes('What would you like to ask? (optional)'))},
{file:'enrollment.html',title:'Childcare Availability & Enrollment | Nana’s Cozy Corner',description:'Ask about infant and toddler childcare availability in Milwaukee. Share your child’s age, start timing, and schedule with Nana’s Cozy Corner.',body:hero('Availability & enrollment','Your child’s next chapter<br>starts with hello.','Looking for infant or toddler care in Milwaukee? Share a few details about your family’s needs. We’ll discuss current openings, tuition, and the next step.',`<div class="actions">${button('#inquiry','Ask about availability')}${button('tel:+14144426262','Call 414-442-6262',true)}</div>`)+section(heading('An easier first step','A conversation before the paperwork.')+steps())+inquiry('availability','Let’s find the right fit.',commonFields()+ageField()+startField()+input('schedule','Days and hours needed *','text','required placeholder="For example, Monday–Friday, 7 a.m.–4 p.m."')+select('transportation','Transportation question? (optional)',['I would like information','I do not need transportation'])+notes())+section(faq([['Does this reserve a place?','No. Our team must confirm an opening, review the required documents, and complete enrollment with your family before care begins.'],['What if there is no opening for my child?','Ask our team about any waitlist options and how to stay in touch about future availability.'],['How do I find out about tuition or help with care?','Our team can discuss current tuition, payment arrangements, and potential program support based on your family’s needs.']]))},
{file:'schedule-a-tour.html',title:'Request a Childcare Tour in Milwaukee | Nana’s Cozy Corner',description:'Request a tour of Nana’s Cozy Corner in Milwaukee. Meet the team, ask about infant and toddler care, and explore whether Nana’s is right for your family.',body:hero('Visit Nana’s','Come with questions.<br>Leave knowing us better.','Meet our team, talk about your child, and explore the care that could be part of your family’s day.',button('#inquiry','Request a tour'))+section(cards([['Meet','Get to know the team','Ask about our approach, experience, and how we support your child’s stage.'],['Explore','Picture your child’s day','Talk through rest, play, meals, classroom routines, and communication with families.'],['Ask','Bring what matters to you','Discuss availability, tuition, the enrollment process, and any support you may need.']]))+inquiry('tour','Tell us when you’d like to visit.',commonFields()+ageField()+input('preferred_date','Preferred date (optional)','date')+select('preferred_time','Preferred time of day (optional)',['Morning','Midday','Afternoon','Please call me to arrange a time'])+notes('Other times that work or questions for your visit (optional)'))+section(`<div class="support-banner"><div><h2>Wait for your tour confirmation.</h2><p>A request is not a booking. Our team will confirm the date and time with you before you arrive.</p><p><strong>4006 N 42nd Street, Milwaukee, WI 53216</strong></p></div>${button(directions,'Get directions',true)}</div>`)},
{file:'contact.html',title:'Contact Nana’s Cozy Corner | Milwaukee Childcare',description:'Call Nana’s Cozy Corner at 414-442-6262. Visit 4006 N 42nd Street, Milwaukee, WI 53216. Open Monday–Friday, 6 a.m.–6 p.m.',body:hero('Contact Nana’s','Let’s talk about<br>your little one.','Questions about care, availability, Early Head Start, or a visit? We’re here to help you take the next step.',`<div class="actions">${button('tel:+14144426262','Call 414-442-6262')}${button('mailto:Info@nanascozycorner.com','Email our team',true)}</div>`)+section(`<div class="contact-grid"><article class="card"><p class="eyebrow">Call or email</p><h2>Say hello.</h2><p>${phone}<br>${email}</p></article><article class="card"><p class="eyebrow">Hours</p><h2>6 a.m.–6 p.m.</h2><p>Monday–Friday<br>Ask about holiday closures.</p></article><article class="card"><p class="eyebrow">Find us</p><h2>Milwaukee, WI</h2><p>4006 N 42nd Street<br>Milwaukee, WI 53216</p><a class="text-link" href="${directions}" target="_blank" rel="noopener">Get directions →</a></article></div>`)+inquiry('contact','What can we help you with?',commonFields()+select('reason','I have a question about…',['Availability and enrollment','Early Head Start','A tour','Transportation','Referrals','Something else'],true)+`<label class="full">Your message *<textarea name="message" rows="4" maxlength="1200" required aria-describedby="privacy-help"></textarea></label>`)+section(`<div class="split"><div>${heading('Getting here','Ask about transportation.')}<p>Our sister company, Cozy Cruisers, can discuss transportation options. Coverage, eligibility, and schedules must be confirmed for your family.</p><a class="text-link" href="https://www.cozycruisermke.com" target="_blank" rel="noopener">Explore Cozy Cruisers →</a></div><div class="quiet-card"><h3>Already part of the family?</h3><p>Use your existing family portal for your current account.</p>${button('https://elv.earlylearningventures.org/elv/login','Family login',true)}</div></div>`)},
{file:'referral-program.html',title:'Cozy Circle Referral Program | Nana’s Cozy Corner',description:'Help another Milwaukee family discover Nana’s Cozy Corner. Learn about the Cozy Circle Referral Program and ask our team about program terms.',body:hero('Cozy Circle Referral Program','Share a little<br>of the cozy.','Know a family looking for childcare? Help them get to know Nana’s Cozy Corner and ask our team about our referral program.',button('#inquiry','Ask about a referral'))+section(`<div class="split"><div>${heading('You earn when they stay','A warm introduction<br>can make a difference.')}<p>Our published referral program offers a base bonus of up to $500, with a potential EHS bonus boost of up to $250. The total potential payout is up to $750, subject to program terms.</p><p>Confirm current terms with our team before referring. EHS eligibility and acceptance must be verified for an EHS bonus.</p></div><div class="quiet-card"><h3>Published program requirements</h3><ul><li>Referrer is a current parent, staff member, or approved community partner.</li><li>The child enrolls full-time and remains active for 60 consecutive calendar days.</li><li>No pending withdrawal or termination notice.</li><li>Maximum two referral payouts per person per quarter.</li><li>Payment follows eligibility confirmation and the retention milestone.</li></ul></div></div>`)+inquiry('referral','Let’s talk about your referral.',commonFields()+select('referrer_type','Your connection to Nana’s',['Current parent','Staff member','Community partner','I would like to ask about eligibility'],true)+notes('Tell us about your referral question (optional)'))+section(`<div class="support-banner"><div><h2>Make the introduction with permission.</h2><p>The easiest start is to share our enrollment page and ask the family to contact Nana’s directly. Please get their permission before sharing someone else’s contact details.</p></div>${button('/enrollment.html','View enrollment page',true)}</div>`)},
{file:'privacy.html',title:'Website Privacy Information | Nana’s Cozy Corner',description:'How Nana’s Cozy Corner handles information shared through this website and how to contact our team with privacy questions.',body:hero('Website information','Your first inquiry<br>can stay simple.','Please share only what we need to respond to your question.',button('/contact.html','Contact our team'))+section(`<div class="prose"><h2>Information you choose to share</h2><p>Our inquiry helpers ask for your name, a phone number or email, and basic care or visit preferences. Do not include children’s full names, medical records, benefit documents, Social Security numbers, or payment details.</p><h2>Email preparation and delivery</h2><p>If the button says “Review email,” the website prepares a message on your device. Nothing is sent until you send it through your email service. You can also call or email our team directly.</p><p>If direct online submission is available, the form will say “Send request.” Those requests are processed by our website host, Vercel, and delivered through Resend to the center’s inquiry inbox. Cloudflare Turnstile helps protect direct submissions from automated abuse. A request is used to respond to your inquiry; it does not automatically sign you up for marketing.</p><h2>Technical records</h2><p>Our hosting provider processes technical request information to deliver and protect the website. We do not put the contact details or child information entered in these forms into marketing analytics. We do not save form contents in browser local storage.</p><h2>Questions</h2><p>To ask about information you have shared or request a correction or deletion, contact ${email} or ${phone}. We will discuss your request and any applicable recordkeeping requirements with you.</p><p class="small">Website information updated October 6, 2026.</p></div>`)},
{file:'404.html',title:'Page Not Found | Nana’s Cozy Corner',description:'Find childcare programs, enrollment information, and contact details for Nana’s Cozy Corner in Milwaukee.',noindex:true,body:hero('Let’s get you back','A little detour.','We couldn’t find that page. Explore our programs or contact our team for help.',`<div class="actions">${button('/','Back to home')}${button('/contact.html','Contact Nana’s',true)}</div>`)}
];

const nav = [['programs.html','Programs'],['about.html','About Nana’s'],['early-head-start.html','Early Head Start'],['contact.html','Contact']];
const business = {'@type':'ChildCare','@id':`${origin}/#business`,name:'Nana’s Cozy Corner',url:origin,telephone:'+1-414-442-6262',email:'Info@nanascozycorner.com',logo:`${origin}/assets/nanas-logo.png`,address:{'@type':'PostalAddress',streetAddress:'4006 N 42nd Street',addressLocality:'Milwaukee',addressRegion:'WI',postalCode:'53216',addressCountry:'US'},openingHoursSpecification:[{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday'],opens:'06:00',closes:'18:00'}]};
const stylesheetVersion = createHash('sha256').update(await readFile('styles.css')).digest('hex').slice(0,10);
const scriptVersion = createHash('sha256').update(await readFile('script.js')).digest('hex').slice(0,10);
await rm('public',{recursive:true,force:true});
await mkdir('public/assets',{recursive:true});
for (const p of pages) {
  const canonical = p.file==='index.html'?`${origin}/`:`${origin}/${p.file}`;
  const graph = {'@context':'https://schema.org','@graph':[business,{'@type':'WebPage','@id':canonical,name:p.title,url:canonical,description:p.description,about:{'@id':`${origin}/#business`}}]};
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(p.title)}</title><meta name="description" content="${escape(p.description)}"><link rel="canonical" href="${canonical}">${p.noindex?'<meta name="robots" content="noindex, follow">':''}<meta property="og:type" content="website"><meta property="og:site_name" content="Nana’s Cozy Corner"><meta property="og:title" content="${escape(p.title)}"><meta property="og:description" content="${escape(p.description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${origin}/assets/hero-classroom.png"><meta property="og:image:alt" content="Nana’s Cozy Corner brand artwork"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#fff8ed"><link rel="icon" href="/assets/favicon.ico" sizes="any"><link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32x32.png"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png"><link rel="stylesheet" href="/styles.css?v=${stylesheetVersion}"><script type="application/ld+json">${JSON.stringify(graph).replaceAll('<','\\u003c')}</script></head>
<body><a class="skip-link" href="#main">Skip to main content</a><div class="utility-bar"><div class="container"><span>Milwaukee childcare · Monday–Friday, 6 a.m.–6 p.m.</span><a href="https://elv.earlylearningventures.org/elv/login" rel="noopener" target="_blank">Family login ↗</a></div></div><header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="Nana’s Cozy Corner home"><img src="/assets/nanas-logo.png" width="84" height="84" alt=""><span>Nana’s Cozy Corner<small>Learn. Grow. Belong.</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="site-nav" type="button">Menu <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="Main navigation">${nav.map(([f,label])=>`<a href="/${f}"${p.file===f?' aria-current="page"':''}>${label}</a>`).join('')}${button('/enrollment.html','Check availability')}</nav></div></header><main id="main">${p.body}</main><footer class="site-footer"><div class="container footer-grid"><div><a class="footer-name" href="/">Nana’s Cozy Corner</a><p>A cozy start. A caring community.<br>Learn. Grow. Belong.</p><p>4006 N 42nd Street<br>Milwaukee, WI 53216</p></div><div><h2>Let’s connect</h2><p>${phone}<br>${email}</p><p>Monday–Friday<br><strong>6 a.m.–6 p.m.</strong></p></div><nav aria-label="Footer navigation"><h2>Your next step</h2><a href="/enrollment.html">Availability & enrollment</a><a href="/schedule-a-tour.html">Request a tour</a><a href="/referral-program.html">Refer a family</a><a href="/early-head-start.html">Early Head Start</a><a href="/privacy.html">Website privacy</a></nav></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Nana’s Cozy Corner</span><span>Milwaukee, Wisconsin · A place to belong.</span></div></footer><div class="mobile-actions" aria-label="Quick contact">${button('tel:+14144426262','Call Nana’s',true)}${button('/enrollment.html','Check availability')}</div><script src="/script.js?v=${scriptVersion}" defer></script></body></html>`;
  await writeFile(p.file,html+'\n');
  await writeFile(`public/${p.file}`,html+'\n');
}
for (const f of ['nanas-logo.png','hero-classroom.png','favicon.ico','favicon-32x32.png','apple-touch-icon.png']) await copyFile(`assets/${f}`,`public/assets/${f}`);
for (const f of ['styles.css','script.js']) await copyFile(f,`public/${f}`);
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.filter(p=>!p.noindex).map(p=>`  <url><loc>${origin}/${p.file==='index.html'?'':p.file}</loc></url>`).join('\n')}\n</urlset>\n`;
const robots = `User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: ${origin}/sitemap.xml\n`;
for (const [name,content] of [['sitemap.xml',sitemap],['robots.txt',robots]]) {await writeFile(name,content);await writeFile(`public/${name}`,content);}
console.log(`Built ${pages.length} pages with canonical URLs, business markup, sitemap, and shared navigation.`);
